name: CI CD for BrewBuddies App

on:
  pull_request:
    branches:
      - master

jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"  # Specify Flutter version here
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"  # Specify Flutter version here
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
